sudo: required

language: python

python:
  - "2.6"
  - "2.7"

services:
  - docker

before_install:
  - echo "key = '7268076c403361ebf9b835d34f0ecd72d139eeb884db2702'" > $TRAVIS_BUILD_DIR/chat/secret_key.py
  - travis_wait 30 docker-compose build
  - docker images

install: "pip install -r requirements.txt"

script:
  - nosetests
  - docker-compose up
  - docker ps -a
